
default_platform(:ios)

platform :ios do

  # Configure
  project = "MyApp"
  xcodeproj = "#{project}.xcodeproj"
  workspace = "#{project}.xcworkspace"
  scheme = project

  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: xcodeproj)

    build_app(workspace: workspace, scheme: scheme)

    commit_version_bump(
      message: 'Build Version Bump',
      xcodeproj: 'SGRadio.xcodeproj',
      force: true
    )
    build_number = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
    add_git_tag(tag: "build-#{build_number}")
    push_to_git_remote(remote: "bitbucket")

    deliver(
      skip_metadata: true,
      skip_screenshots: true,
    )
  end

  desc "Push metadata and screenshots"
  lane :deliver_meta do
    deliver(
      skip_binary_upload: true
    )
  end

end
